spring:
  application:
    name: dynamic-bean
  datasource:
    url: jdbc:mysql://192.168.33.128:3306/dynamic_bean?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: dynamic-bean-hikari
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 10
      validation-timeout: 5000
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://192.168.33.128:6379"
        codec: !<org.redisson.client.codec.StringCodec> {}
logging:
  level:
    org.mybatis: info
    org.redisson: info
    org.redisson.connection: info
    org.redisson.client: info
canal:
  server-host: 192.168.33.128
  server-port: 11111
  destination: example
  username: canal
  password: canal
  subscribe-filter: dynamic_bean.refresh_bean

dynamic-bean:
  mode: redis #database || redis || database-auto